services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
      - /src/node_modules
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
  db:
    image: mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3309:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./Database.sql:/docker-entrypoint-initdb.d/Database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - ./.env
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
